name: turtlz

description: turtlz application.

publish_to: 'none'

version: 1.0.2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # network
  dio:
  platform:
  build_runner:
  package_info:
  json_annotation:
  shared_preferences:
  json_serializable: ^4.1.0

  formz: ^0.4.0
  logger: ^1.1.0
  freezed: ^0.14.1
  equatable: ^2.0.3

  # login
  kakao_flutter_sdk: ^1.1.1
  sign_in_with_apple: ^3.2.0

  # fcm
  firebase_core: ^1.13.1
  firebase_messaging: ^11.2.4
  flutter_local_notifications: ^9.5.2
  firebase_messaging_platform_interface:

  # web
  url_strategy: ^0.2.0
  vrouter: ^1.2.0+21
  firebase_core_web:
  universal_html: ^2.0.8
  firebase_messaging_web: ^2.4.0
  url_launcher_web: 2.0.6

  # bloc
  bloc: ^7.2.1
  flutter_bloc: ^7.3.3

  # webview
  flutter_html: ^2.2.1
  webview_flutter: ^2.0.4

  # analytics
  amplitude_flutter: ^3.9.0
  firebase_analytics: ^9.1.7

  # helpers
  flutter_svg: ^0.23.0
  currency_formatter: ^1.2.1
  permission_handler: ^9.2.0
  wrapped_korean_text: ^0.0.2
  flutter_swiper_plus: ^2.0.4
  flutter_svg_provider: ^0.1.11
  flutter_native_splash: ^1.3.3
  carousel_slider: ^4.1.1
  extended_tabs: ^2.3.0

  # payment
  bootpay: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/icons/bottomNavigationBar/
    - assets/images/


flutter_native_splash:

  #  background_image: assets/images/splash_screen.png
  #  web_image_mode: cover
  full_screen: true
  android: true
  ios: true
  web: true
