// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAi2Y06-KOzOPfW9Y4Rd_QxcWTAm2aGi80',
    appId: '1:353560109519:web:73d67beb9e720c52d9f2ba',
    messagingSenderId: '353560109519',
    projectId: 'turtlz',
    authDomain: 'turtlz.firebaseapp.com',
    storageBucket: 'turtlz.appspot.com',
    measurementId: 'G-J2FQ5XDEEM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3lOsZ1l7q_nqW6a29BQs1wwIBZ20Govk',
    appId: '1:353560109519:android:e67a68d98da46260d9f2ba',
    messagingSenderId: '353560109519',
    projectId: 'turtlz',
    storageBucket: 'turtlz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpV4BvOmL3rHTocrzDWX24DrfgS4nlvrY',
    appId: '1:353560109519:ios:a2905b3702d2a58ad9f2ba',
    messagingSenderId: '353560109519',
    projectId: 'turtlz',
    storageBucket: 'turtlz.appspot.com',
    androidClientId:
        '353560109519-nf42i1gj1spfmqm45hf8pv19nubf0mj0.apps.googleusercontent.com',
    iosClientId:
        '353560109519-kqjfno8bn7fec9kb3aodkoacn61k6nd1.apps.googleusercontent.com',
    iosBundleId: 'co.loonshot.turtlz',
  );
}
